### ISSUE TITLE
Where can I find the 'log event calculations' in node red. 

### ISSUE THREAD

**Issue by ToonMeynen** [freakent/node-red-contrib-sunevents#14]
This is not a bug but rather a request for some extra information😉
I've read all the documentation in node red but some things still aren't clear to me. 

You mentioned:
_If you enable the "Log event calculations?", you will be able to see all these calculations taking place each day._
Where exactly in node red can I find this information? I attached a debug node to the sun-event node and checked all the context tabs but nothing shows up. I'm relatively new to node red.  

The flow picture you attached is great but it's not really useful to learn from without the flow code. Do you have some example flow code as well so I can import them and have a look at the functions. For example, a simple flow that trigger on sunrise or sunset would be wonderful to get me going on my home-automation project. 

Thanks in advance.

**Comment by freakent** [comment]
To see the calculations I just do a console.out so you’d need view the nodejs console. 

My own nodered setup is years old, so probably won’t work for you.  If you connect a debug node to the output of the sunevents node you’ll see the payload. Just connect the output of sunevents to a filter node to only continue for the event you are interested in.

**Comment by freakent** [comment]
Feature has been removed in v3.0. The node now displays the next scheduled event in its status.
