### ISSUE TITLE
Consistent crash with version 3.02

### ISSUE THREAD

**Issue by swilson86** [freakent/node-red-contrib-sunevents#24]
Since version 3.02 I have been seeing this error:

17 Mar 12:56:51 - TypeError: Cannot set property 'sunevent' of null
    at SunEventsNode.node.sunevent (C:\Users\Scott\.node-red\node_modules\node-red-contrib-sunevents\lib\sun-events-node.js:74:25)
    at Timeout._fireEvent [as _onTimeout] (C:\Users\Scott\.node-red\node_modules\node-red-contrib-sunevents\lib\sun-events.js:80:22)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7)

**Comment by freakent** [comment]
Can you upload the relevant section from your flow?

**Comment by swilson86** [comment]
[{"id":"aaf2b0ed.593cd","type":"inject","z":"aa402570.4ef838","name":"","props":[{"p":"payload"}],"repeat":"43200","crontab":"","once":true,"onceDelay":"0.5","topic":"","payload":"1","payloadType":"str","x":90,"y":300,"wires":[["5b791f09.f3a0d"]]},{"id":"5b791f09.f3a0d","type":"function","z":"aa402570.4ef838","name":"Lat/Lon","func":"/* The end user sets this up once \nin the Setup tab within node-red and then\nit feeds to any node that requires a latitude and\nlongitude. Thus you should not set lon/lat within\nSunup/Sunset manually (leave it empty for portability).\n*/\n\nvar lon = global.get(\"longitude\");\nif (lon === undefined) {\n    node.status({fill:\"red\",shape:\"dot\",text:\"longitude undefined\"});\n    return null;\n}\nvar lat = global.get(\"latitude\");\nif (lat === undefined) {\n    node.status({fill:\"red\",shape:\"dot\",text:\"latitude undefined\"});\n    return null;\n}\n\nnode.status({fill:\"green\",shape:\"dot\",text:lat+\", \"+lon});\n\nmsg.payload = {\n    \"lng\": parseFloat(lon),\n    \"lat\": parseFloat(lat)\n};\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":230,"y":300,"wires":[["bcadb643.837398","e71992a8.d7f44"]]},{"id":"e71992a8.d7f44","type":"debug","z":"aa402570.4ef838","name":"Lat/Long","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":420,"y":360,"wires":[]},{"id":"23aca70c.cbd538","type":"debug","z":"aa402570.4ef838","name":"Sun Event","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":590,"y":300,"wires":[]},{"id":"bcadb643.837398","type":"sun events","z":"aa402570.4ef838","testmode":false,"verbose":true,"topic":"","name":"Sun events","x":410,"y":300,"wires":[["23aca70c.cbd538"]]},{"id":"a1d01bb6.d18678","type":"inject","z":"aa402570.4ef838","name":"Startup","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":100,"y":180,"wires":[["776c3fe2.8ce0a"]]},{"id":"776c3fe2.8ce0a","type":"function","z":"aa402570.4ef838","name":"Latitude Longitude","func":"/* Set your latitude and longitude in decimal form, and surrounded by quotation marks.\nNote: Darksky asks you to enter these numbers in its setup function */\nvar latitude = \"20.177741\";\nvar longitude = \"-87.812107\";\n\n\nglobal.set(\"latitude\",latitude);\nglobal.set(\"longitude\",longitude);\nnode.status({fill:\"black\",shape:\"dot\",text:latitude+\",\"+longitude});","outputs":1,"noerr":0,"initialize":"","finalize":"","x":270,"y":180,"wires":[[]]},{"id":"14850151.bbfd1f","type":"comment","z":"aa402570.4ef838","name":"Setup","info":"Current latitude/longitude along with a myriad of end user settings is done on the Setup tab.","x":80,"y":140,"wires":[]},{"id":"2a7cde63.62d512","type":"comment","z":"aa402570.4ef838","name":"Astro Events","info":"On the Astro Events tab there are several flows which get their unique end user settings like latitude/longitude, cloud cover, etc from the Setup tab.","x":90,"y":260,"wires":[]}]

**Comment by swilson86** [comment]
The flow above seems to fail just after an event. I am running it on a a windows machine and have just copied the flow to test on a Raspberry Pi running Buster. A really nice enhancement is for Sun events to immediately return the next event or the previous (current) event. If node-red crashes it is possible to have missed a sun event such as dusk. When that occurs the outside lights will not be on after a restart. Knowing the current event would be easier for downstream programming. But that's a separate request... first to find out why it crashes.

**Comment by freakent** [comment]
I've not been able to recreate this issue in testing, but I have performed a few extra checks. I've just pushed a new version. Please give v3.0.3 a try.

**Comment by swilson86** [comment]
Version 3.03 works ok on Windows! Since this is the first time it hasn't crashed I noticed that events prior to version 3 used only msg.payload to receive an event name. Had to change all the downstream functions to check msg.payload.sunevent or msg.sunevent which you have documented but it easily missed. Thanks for the speedy fix on 3.03 !!

**Comment by freakent** [comment]
That’s good news. Thank you for providing the feedback. 

Since this node now accepts an input payload, I thought it important not to overwrite or loose any values already in the msg.payload. So I put the event name in msg.payload.sunevent. I could make that clearer in the upgrading section of the readme.
