### ISSUE TITLE
Documentation Enhacement

### ISSUE THREAD

**Issue by Braehead** [freakent/node-red-contrib-sunevents#30]
If you could please:

1) A list of the events in their respective pairs.  I know they are fairly obvious, but sometimes I get a brain freeze with a random list ;)

2) A second list of the events in the order they occur over 24hrs, starting at some logical point in the day.

Many thanks for the consideration.

**Comment by martin-jarvis** [comment]
Hi, The list of events returned by Suncalc is documented here:
https://github.com/mourner/suncalc



Property | Description
-- | --
sunrise | sunrise (top edge of the sun appears on the horizon)
sunriseEnd | sunrise ends (bottom edge of the sun touches the horizon)
goldenHourEnd | morning golden hour (soft light, best time for photography) ends
solarNoon | solar noon (sun is in the highest position)
goldenHour | evening golden hour starts
sunsetStart | sunset starts (bottom edge of the sun touches the horizon)
sunset | sunset (sun disappears below the horizon, evening civil twilight starts)
dusk | dusk (evening nautical twilight starts)
nauticalDusk | nautical dusk (evening astronomical twilight starts)
night | night starts (dark enough for astronomical observations)
nadir | nadir (darkest moment of the night, sun is in the lowest position)
nightEnd | night ends (morning astronomical twilight starts)
nauticalDawn | nautical dawn (morning nautical twilight starts)
dawn | dawn (morning nautical twilight ends, morning civil twilight starts)

Respective pairs doesn't make sense for nadir, night. dusk etc.

**Comment by freakent** [comment]
Hi, The list of events returned by Suncalc is documented here:
https://github.com/mourner/suncalc



Property | Description
-- | --
sunrise | sunrise (top edge of the sun appears on the horizon)
sunriseEnd | sunrise ends (bottom edge of the sun touches the horizon)
goldenHourEnd | morning golden hour (soft light, best time for photography) ends
solarNoon | solar noon (sun is in the highest position)
goldenHour | evening golden hour starts
sunsetStart | sunset starts (bottom edge of the sun touches the horizon)
sunset | sunset (sun disappears below the horizon, evening civil twilight starts)
dusk | dusk (evening nautical twilight starts)
nauticalDusk | nautical dusk (evening astronomical twilight starts)
night | night starts (dark enough for astronomical observations)
nadir | nadir (darkest moment of the night, sun is in the lowest position)
nightEnd | night ends (morning astronomical twilight starts)
nauticalDawn | nautical dawn (morning nautical twilight starts)
dawn | dawn (morning nautical twilight ends, morning civil twilight starts)

Respective pairs doesn't make sense for nadir, night. dusk etc.
