### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by aaron1uk** [freakent/node-red-contrib-sunevents#34]
Firstly great little Node, I have a feature Request, instead of waiting and getting the next solar event it would be beneficial to return the current solar event (or the closest solar event) instantly.

**Comment by freakent** [comment]
This is has been asked before. The whole point of this node is to output the events when they happen. If you just want to find the next event or the last event you can do it with 4 simple lines of Javascript in a Function node. I already provided an example before here https://github.com/freakent/node-red-contrib-sunevents/issues/28#issuecomment-877872960

**Comment by aaron1uk** [comment]
apologies must have missed that thanks for the reply
