### ISSUE TITLE
Sunevent sends warnings

### ISSUE THREAD

**Issue by mweissen** [freakent/node-red-contrib-sunevents#38]
A good program. I would like to use this node, but the node keeps writing warnings. I think I now have three options:

(1) I wait for this spam to be turned off with an option.
(2) I build a fork that does not contain these spam messages.
(3) I use another node.

As I have seen, I am not the only one who is bothered by the spam.

**Comment by freakent** [comment]
option 4 ask nicely.

This is something I wrote for my own use some years ago and shared with the community. I no longer use it myself but keep it up to date to help others. I don't charge for this software and hardly anyone has used my "buy me a coffee" link. 

I previously explained my reasons for outputting this message. A number of home assistant users didn't understand that the node only outputs when timers fire. When they send me a log file I can demonstrate it is working as designed.

**Comment by freakent** [comment]
or option 5, send me a pull request. After all this is open source software.

**Comment by freakent** [comment]
By the way, last person who complained it was outputting too many warnings was actually using the node incorrectly. If you are using it correctly then it should at most notify you it is initialising the timers once a day. If you see it more than once a day it may mean you don't understand how it works.
