### ISSUE TITLE
Too long events calculation: it takes more than 5 minutes to calculate events

### ISSUE THREAD

**Issue by AlexBokhankovich** [freakent/node-red-contrib-sunevents#39]
Please see screenshot below
NR v2.1.6

![image](https://user-images.githubusercontent.com/3011471/175813799-3d757342-7a8d-4c7b-9ab8-fceeebdf6aa5.png)

**Comment by freakent** [comment]
Alex, please look at closed issues. This has been asked before. I can assure you it is not taking more than 5 minutes to calculate the events. Look at the green status telling you which event will fire next. 

Regards,
Martin

+44 7776490601

**Comment by AlexBokhankovich** [comment]
> Alex, please look at closed issues. This has been asked before. I can assure you it is not taking more than 5 minutes to calculate the events. Look at the green status telling you which event will fire next. Regards, Martin +44 7776490601
> […](#)
> On 26 Jun 2022, at 13:22, Alexander Bokhankovich ***@***.***> wrote: ﻿ Please see screenshot below NR v2.1.6 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "#39", "url": "#39", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Thank you for your help. It is now so obvious to understand its logic. Now I got it. I was expecting once the node is called it returns an array of events with corresponding times.

**Comment by freakent** [comment]
If you want just a list of events then use SunCalc directly. I included a function example on how to do that in one of those closed issues. 

Regards,
Martin

+44 7776490601
