### ISSUE TITLE
Output is "calculating sunevents for lat X and lng -Y" Until Next Sun Event

### ISSUE THREAD

**Issue by BillyFKidney** [freakent/node-red-contrib-sunevents#41]
Whenever I inject into the _Sun Events_ node the output is:
`calculating sunevents for lat X and lng -Y`
![image](https://user-images.githubusercontent.com/65253277/179121742-03201fea-a6bc-495f-b30a-41683ed36ab4.png)
(coordinates removed for privacy)

I don't receive the full payload with the current sun event **until** the next sun event occurs (in this case, goldenHour)
<img width="653" alt="image" src="https://user-images.githubusercontent.com/65253277/179121543-9900d9cd-5749-4118-9e6e-7b429bf0af7e.png">

How can I get the output of _Sun Events_ once the calculations are complete?

**Comment by freakent** [comment]
Please take a look at the closed issues. This has been asked before. This SunEvents node takes the calculations made by the library SunCalc and turns them into timed events. If you want just a list of the calculations call SunCalc directly. I have provided an example function node. It's just 3 or 4 lines long.

**Comment by freakent** [comment]
See #28

**Comment by freakent** [comment]
I just noticed, it was you who raised #28 already.

**Comment by BillyFKidney** [comment]
Apologies, I had everything crash and I’m rebuilding again. 

I’m still a rookie with all of this. 🥺
