### ISSUE TITLE
Reduce event logging

### ISSUE THREAD

**Issue by kuema** [freakent/node-red-contrib-sunevents#8]
Hi,

first, thanks for this node! I've been using it for ages now. 😄 

Would it be possible to reduce this log output to debug or use the "Log event calculations?" flag? It can get quite noisy and I can't see the benefit of logging this during normal operation.

https://github.com/freakent/node-red-contrib-sunevents/blob/be719ec272c6bf27d8efb82b3a48ff72f212ba8d/sunevents-node.js#L57

**Comment by freakent** [comment]
Thanks for the feedback! Yes, now that the timezone issue has been resolved I can do something about reducing the amount of debug info that is output. Watch this space.

**Comment by freakent** [comment]
Removed all that logging.
